version: "2.1"
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver-testing
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=thisStrong(!)Password
    ports:
      - 41707:1433
    restart: unless-stopped